<a href="https://colab.research.google.com/github/JoshRome/ai_course/blob/master/HW_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

The code below will take a list of numpy arrays of matrices which will be multiplied together in a for loop until the final output matrix is printed. It will take a list of the entire input of matrices and pop the first matrix which will be stored as prev and will then be multiplied with the next matrix until there are no more pairs to multiply. We make a simple exception checker that will display which pair of matrices cause an error when multiplying.

In [0]:
def multiply_matrices(products):
  matrices = products
  prev = matrices.pop(0)

  try:
    for next in matrices:
      prev = np.matmul(prev, next)

  except ValueError as error:
    print(error)
    print("Fault pairs involved:\n" + str(prev) + ",\n" + str(next) + "\n")
    prev = np.array([0])
  
  return prev


This Working Test Case shows what happens when you multiply a 2 x 2 matrix and displays the correct answer. 

In [24]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

output = multiply_matrices([a,b])
print(output)

[[19 22]
 [43 50]]


This next test case will show the error handeling of when you try to multiply a matrix with a bad pair. 

In [27]:
c = np.array([[1, 2], [3, 4]])
d = np.array([[5, 6], [7, 8]])

output = multiply_matrices([c,80])
print(output)

matmul: Input operand 1 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)
Fault pairs involved:
[[1 2]
 [3 4]],
80

[[1 2]
 [3 4]]
